name: SpigotUtils
description: A Spigot plugin to make plugin development easier.
author: Tim van Dijkhuizen
version: "1.2.2"
api-version: 1.13
main: nl.timvandijkhuizen.spigotutils.SpigotUtils
load: STARTUP